### ISSUE TITLE
toolchain links / scripts

### ISSUE THREAD

**Issue by SaicharanKandukuri** [A51-Development/kernel_samsung_a51#1]
Hey there @roynatech2544
I am trying to compile these sources but can't get the correct toolchain
can you give any links to get the toolchain

**Comment by Royna2544** [comment]
@SaicharanKandukuri I use https://gist.github.com/roynatech2544/0feeeb35a6d1782b186990ff2a0b3657
For setuping my clang toolchain

**Comment by SaicharanKandukuri** [comment]
Thanks
