### ISSUE TITLE
Adding kernel parameters

### ISSUE THREAD

**Issue by macvenez** [A51-Development/kernel_samsung_a51#11]
Hi! I'd like to add some kernel parameters in order to be able to run Docker in Termux but I don't know which files to edit and whether there's something like a menuconfig where we can see all the features that can be enabled.

OT: Is it possible to flash this Kernel and use it with the stock Samsung ROM?

Thanks!

**Comment by ratatouille100** [comment]
Hello there. It's possible to use it with the stock ROM. There are two versions: for AOSP and OneUI. There's menuconfig, you have to set two variable ARCH and CROSS_COMPILE and then write something like that: 
```
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- menuconfig
```

**Comment by ThePolishLemon** [comment]
> Hello there. It's possible to use it with the stock ROM. There are two versions: for AOSP and OneUI. There's menuconfig, you have to set two variable ARCH and CROSS_COMPILE and then write something like that:
> 
> ```
> make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- menuconfig
> ```

Hey, i'm kind of a noob, said command generates a .config file, but the Makefile doesn't allow you to build the kernel with said config file present, is there a way to work around that ?
also trying to run docker in termux XD
