### ISSUE TITLE
make: *** [Makefile:146: sub-make] Error 2

### ISSUE THREAD

**Issue by Prythomn** [A51-Development/kernel_samsung_a51#16]
When compiling the kernel, the following error appears

**Comment by Prythomn** [comment]
@roynatech2544 any fix?

**Comment by MichaelK-F** [comment]
I think there is an issue with the latest commit. I would revert to this commit: [https://github.com/Roynas-Android-Playground/kernel_samsung_universal9611/commit/29e4190f27cbd01ff913616e898fa7dafe564066](https://github.com/Roynas-Android-Playground/kernel_samsung_universal9611/commit/29e4190f27cbd01ff913616e898fa7dafe564066)

**Comment by Royna2544** [comment]
> I think there is an issue with the latest commit. I would revert to this commit: [29e4190](https://github.com/Roynas-Android-Playground/kernel_samsung_universal9611/commit/29e4190f27cbd01ff913616e898fa7dafe564066)

21be80e38e880170de393ac719ca171d17bd1717
