### ISSUE TITLE
mq schedulers are unstable 

### ISSUE THREAD

**Issue by ghazzor** [A51-Development/kernel_samsung_a51#17]
they cause weird issues , like reboot to recovery breaks , kernel panics (very rare but happens) , freezes (on kyber) , you cant even power off the phone , it just reboots 

m21 aosp 13 (leaf os)

i flashed stock , so don't have logs rn

**Comment by Royna2544** [comment]
ok, ill revert

**Comment by Royna2544** [comment]
Thanks (Applied as b05037a3ba74cdddc00ae4ff26018d3ab3c1e787)
