### ISSUE TITLE
Why don't you add support also for Tab S6 Lite 2020?

### ISSUE THREAD

**Issue by Fede2782** [A51-Development/kernel_samsung_a51#20]
This is just a suggestion and feel free to close the issue. In case you want to see I maintain a up to date kernel source for Tab S6 Lite 2020 (Exynos 9611) and I am available to help

**Comment by Royna2544** [comment]
ok (Commenting not to ignore, will see later)

**Comment by Fede2782** [comment]
Closed because of #32 

Remember to add "Tab S6 Lite" in the repo's description
