### ISSUE TITLE
support for m31?

### ISSUE THREAD

**Issue by SaicharanKandukuri** [A51-Development/kernel_samsung_a51#3]
Hello again @roynatech2544 
i tried to compile & flash the kernel on my m31 device but it resulted in bootloop system
i tried `oneui` , `aosp` & `stock` Targets but all of em leads to bootloop

is these sources support m31?

**Comment by roynatech2544** [comment]
@SaicharanKandukuri

**Comment by Royna2544** [comment]
![IMG_20230605_153747_000](https://github.com/Exynos9611-Development/kernel_samsung_universal9611/assets/69458352/50ecfc47-867d-4ba1-a142-a95c10726804)
This rom uses my source and it's shipped on my AOSP ROMs and no one ever complained

**Comment by SaicharanKandukuri** [comment]
well I tried to pack.sh with `Image` binary and flashed it

**Comment by SaicharanKandukuri** [comment]
I am using it in stock One UI 4
baseband `S3CVD1`

is there any special instructions to compile and flash
help please

**Comment by SaicharanKandukuri** [comment]
nvm
