### ISSUE TITLE
The required file cannot be created or found 

### ISSUE THREAD

**Issue by dpentx** [A51-Development/kernel_samsung_a51#33]
`bash <(curl https://gist.githubusercontent.com/roynatech2544/0feeeb35a6d1782b186990ff2a0b3657/raw/b170134a94dac3594df506716bc7b802add2724b/setup.sh)`

When I ran this code on gitpod, it gave me a file not found error. When I pasted the given url into my own browser, I got the same error. Do you have any suggestions?

**Comment by Royna2544** [comment]
well time to update that link, use weebx clang https://github.com/XSans0/WeebX-Clang
clone it under toolchain/
and others are same

**Comment by dpentx** [comment]
`Make toolchain avaliable at /workspace/kernel_samsung_universal9611/toolchain`
i'm getting an error in the form, is there a way to get over it? and I'm sorry, this is the first time I'm dealing with the kernel

**Comment by beyazdroid** [comment]
i did a full installation of ubuntu on my computer and solved the problem, and the performance has significantly increased. thanks.

**Comment by dpentx** [comment]
i did a full installation of ubuntu on my computer and solved the problem, and the performance has significantly increased. thanks.
