### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by cat658011** [A51-Development/kernel_samsung_a51#38]
``` 
  CC      drivers/net/wireless/scsc/hip4.o
  CC      net/xfrm/xfrm_proc.o
../drivers/net/wireless/scsc/hip4.c:914:5: error: unused variable 'i' [-Werror,-Wunused-variable]
  914 |         u8 i;
      |            ^
../drivers/net/wireless/scsc/hip4.c:2817:5: error: unused variable 'i' [-Werror,-Wunused-variable]
 2817 |         u8 i;
      |            ^
../drivers/net/wireless/scsc/hip4.c:2849:5: error: unused variable 'i' [-Werror,-Wunused-variable]
 2849 |         u8 i;
      |            ^
../drivers/net/wireless/scsc/hip4.c:2879:5: error: unused variable 'i' [-Werror,-Wunused-variable]
 2879 |         u8 i;
      |            ^
4 errors generated.
```

Again, related with https://github.com/Roynas-Android-Playground/kernel_samsung_universal9611/commit/a50a543e4e0ce3e2a54e970a776966a0a8f9d00e

**Comment by Fede2782** [comment]
No, this is fixed by https://github.com/Roynas-Android-Playground/kernel_samsung_universal9611/commit/a50a543e4e0ce3e2a54e970a776966a0a8f9d00e

Builds correctly for me

**Comment by cat658011** [comment]
bruh

**Comment by Fede2782** [comment]
Sorry, you're right. This issue seems to be present when building for devices without Samsung SCSC wireless driver. But the fix seems to be already done https://github.com/Roynas-Android-Playground/kernel_samsung_universal9611/commit/d9506da04c7606368554c06fe4005ca37ca1f78e
