### ISSUE TITLE
kernel build error

### ISSUE THREAD

**Issue by mishustick123** [A51-Development/kernel_samsung_a51#5]
../arch/arm64/mm/init.c:237:17: error: use of undeclared identifier 'ZONE_DMA'
                max_zone_pfns[ZONE_DMA] = PFN_DOWN(max_zone_dma_phys());
                              ^
1 error generated.

**Comment by mishustick123** [comment]
![Screenshot from 2023-07-18 14-06-46](https://github.com/Exynos9611-Development/kernel_samsung_universal9611/assets/71722755/956ae9c2-0b40-4fcb-bdd2-ff0a5183c9d2)

**Comment by Royna2544** [comment]
@mishustick123 And how I know which defconfig used?

**Comment by Kennnzyy** [comment]
@roynatech2544 Hahah
