### ISSUE TITLE
KernelSU update.

### ISSUE THREAD

**Issue by Gojikovi** [A51-Development/kernel_samsung_a51#6]
Hi, could you update KernelSU please? 🥺
I can't use KernelSU ≥ 0.6.2 because the version is too low for new managers.
I use the latest version of the kernel: GrassKSU-AOSP-a51_20230727.
![Screenshot_20230811-172125_KernelSU](https://github.com/Exynos9611-Development/kernel_samsung_universal9611/assets/96128712/bf0f776e-b8e9-4f4f-a0b4-d0f474d04f6e)

**Comment by Royna2544** [comment]
ok wait

**Comment by Royna2544** [comment]
[GrassKSU-AOSP-a51_20230824.zip](https://github.com/Exynos9611-Development/kernel_samsung_universal9611/files/12437798/GrassKSU-AOSP-a51_20230824.zip)
Sorry for the delay, test this and see if it works for you

**Comment by Gojikovi** [comment]
![Screenshot_20230825-162957_KernelSU](https://github.com/Exynos9611-Development/kernel_samsung_universal9611/assets/96128712/27df9891-4b4a-4cfe-b660-0cf0cb54c24b)

It works just great, thank you so much! 😘
