### ISSUE TITLE
How to build the kernel?

### ISSUE THREAD

**Issue by ratatouille100** [A51-Development/kernel_samsung_a51#7]
Hi, I've got a question. How to build this kernel with and without KernelSU, for AOSP and OneUI? I don't quite understand... Thank you

**Comment by pachdomenic** [comment]
KSU is disabled by default.
and for building ONEUI or AOSP kernel you need to change 1 line in build_kernel.sh

**Comment by Royna2544** [comment]
> Hi, I've got a question. How to build this kernel with and without KernelSU, for AOSP and OneUI? I don't quite understand... Thank you

Read readme i added it now
